export const DispatchEvent = {
  Ready: "READY",
  Resumed: "RESUMED",
  MessageCreate: "MESSAGE_CREATE",
  MessageUpdate: "MESSAGE_UPDATE",
  MessageDelete: "MESSAGE_DELETE",
  ChannelCreate: "CHANNEL_CREATE",
  ChannelUpdate: "CHANNEL_UPDATE",
  ChannelDelete: "CHANNEL_DELETE",
  MemberAdd: "MEMBER_ADD",
  MemberUpdate: "MEMBER_UPDATE",
  MemberRemove: "MEMBER_REMOVE",
  RoleCreate: "ROLE_CREATE",
  RoleUpdate: "ROLE_UPDATE",
  RoleDelete: "ROLE_DELETE",
  PresenceUpdate: "PRESENCE_UPDATE",
  TypingStart: "TYPING_START",
  ReactionAdd: "REACTION_ADD",
  ReactionRemove: "REACTION_REMOVE",
  ThreadCreate: "THREAD_CREATE",
  ThreadUpdate: "THREAD_UPDATE",
  ThreadDelete: "THREAD_DELETE",
  InviteCreate: "INVITE_CREATE",
  InviteDelete: "INVITE_DELETE",
  WebhookUpdate: "WEBHOOK_UPDATE",
  EmojiUpdate: "EMOJI_UPDATE",
  ServerUpdate: "SERVER_UPDATE",
  SlashCommandInvocation: "SLASH_COMMAND_INVOCATION",
} as const;

export type DispatchEvent = (typeof DispatchEvent)[keyof typeof DispatchEvent];
